import config
from config import *


language = {
    'RU':{
        "Account":"Счет",
        "Attach a photo of your car": "Прикрепите фото Вашего автомобиля",
        "Confirm entry or correct value": "Подтвердите ввод или исправьте значение",
        "Confirm": "Подтвердить",
        "Client form": "Анкета",
        "Driver form":"Анкета",
        "Do you confirm your phone?": "Подтвердите телефон",
        "Do you confirm your amount?": "Подтвердите сумму",
        "Do you confirm?": "Do you confirm?",
        "Enter phone number?": "Укажите номер телефона?",
        "Enter the sender's wallet":"Укажите кошелек отправителя",
        "Free drivers": "Свободные водители",
        "How much do you want to pay?": "Сколько Вы готовы заплатить?",
        "I looking for a clients": "Я ищу пассажиров",
        "I looking for a taxi": "Я ищу такси",
        "I dont understand this message. Use the menu to get started": "Я не понимаю это сообщение. Используйте меню чтобы начать",
        "May be entered number only": "Укажите число",
        "Make an order":"Сделать заказ",
        "My current location": "Мое текущее местоположение",
        "My destination location": "Мой пункт назначения",
        "My orders": "Мои заказы",
        "Number of digits is incorrect": "Кол-во цифр от 11 до 12",
        "You can input from 1 to 10 digits": "Можно ввести от 1 до 10 цифр",
        "Only digits can be entered": "Могут быть указаны только цифры",
        "Only digits can be entered as a phone number": "В качестве номера телефона могут быть указаны только цифры",
        "Only digits can be entered as a amount": "В качестве суммы могут быть указаны только цифры",
        "yes":"да",
        "no":"нет",
        ", do you confirm your name?": ", подтвердите имя?",
        "Orders":"Заказы",
        "Phone is required, set it in client form":"Телефон обязателен для заполнения, укажите пожалуйста его в анкете",
        "Profile":"Профиль",
        "Set departure location": "Укажите координаты отправления",
        "Set destination location": "Укажите координаты назначения",
        "Thank you for an order":"Спасибо за заказ",
        "Thank you, we will check the crediting of funds":"Спасибо, мы проверим зачисление средств",
        "Thanks for the information.": "Спасибо за указанную информацию",
        "This order cannot be taken, it is already taken":"Этот заказ нельзя взять, он уже занят другим водителем",
        "To use the service you need to enter some data":"Чтобы пользоваться сервисом необходимо ввести некоторые данные",
        "To work in the system, you must have at least {minAmount:d} usdt on your account. To replenish the account, you need to transfer the currency to the specified crypto wallet": "Для работы в системе необходимо иметь на счету не меньше {minAmount:d} usdt. Чтобы пополнить счёт необходимо перевести валюту на указанный криптокошелёк",
        "Unable to find customer":"Не удалось найти клиента",
        "Under construction..": "В разработке..",
        "What time do you need a taxi?": "В какое время вам нужна машина?",
        "What's your name?": "Как вас зовут?",
        "What's your car number?":"What's your car number?",
        "we are already looking for drivers for you...": "Мы уже ищем водителей для Вас...",
        "We couldn't find your profile":"Мы не смогли найти ваш профиль",
        "We saved your name":"Мы сохранили Ваше имя",
        "We saved your phone":"Мы сохранили Ваш телефон",
        "We saved your amount":"Мы сохранили Вашу сумму",
        "Welcome! Use the menu to get started.": "Добро пожаловать! Используйте меню чтобы начать",
        "We are looking for clients for you already":"Мы уже ищем клиентов для Вас",
        "You are in the client menu": "Вы находитесь в меню клиента",
        "You are in the driver menu": "Вы находитесь в меню водителя",
        "You can attach your photo if you wish": "Прикрепите Ваше фото",
        "You cant see orders, your balance is less than {minAmount:d} usdt":"Вы не можете видеть заказы, Ваш баланс менее {minAmount:d} usdt",
        "You have taken the order go to the passenger":"Вы приняли заказ, направляйтесь к пассажиру",
        "Your balance is {driverBalance:d} usdt, min balance for use bot is {minBalance:d} usdt": "Ваш баланс {driverBalance:d} usdt, минимальный баланс для работы в системе {minBalance:d} usdt",
        "How to top up an account":"Как пополнить баланс?",
        "My profile":"Мой профиль",
        "Now":"Прямо сейчас",
        "After 10 minutes":"Через 10 минут",
        "After 15 minutes":"Через 15 минут",
        "In 30 minutes":"Через 30 минут",
        "In one hour":"Через час",
        "In 2 hours":"Через 2 часа",
        "Book an order":"Взять заказ",
        "Copy wallet":"Скопировать кошелек",
        "Confirm the transfer":"Подтвердить перевод",



    },
    'EN':{},
}


def t (alias):
    return language[LANGUAGE][alias]
